### ISSUE TITLE
VIA app do  not recognice my BM60rgbISO_rev2

### ISSUE THREAD

**Issue by eche86** [the-via/keyboards#1400]
I've flashed the last frimware kprepublic_bm60hsrgb_iso_rev2_via.hex but the app do not recognice ("Searching  for devices...").

**Comment by yiancar** [comment]
Hello Please try multiple USB ports and also another computer if you have it.
Sadly I do not have the keyboard here to try myself.

**Comment by eche86** [comment]
Thanks for  your quick response.
I tried in app and web in two laptops in multiple USB ports.
The PCB is new, is it possible a hardware issue? I tried QMK configuration and it works.
Regards

**Comment by yiancar** [comment]
I dont really know if I am honest, worth compiling the firmware with a via keymaps as well

**Comment by Xelus22** [comment]
That's because the BM60HSRGB ISO version is not merged into this repository.

it exists in QMK, https://github.com/qmk/qmk_firmware/blob/master/keyboards/kprepublic/bm60hsrgb_iso/rev2/info.json, but there is no equivalent for VIA json. 
https://github.com/the-via/keyboards/tree/master/src/kprepublic
aka it doesnt exist in here ^

**Comment by peepeetee** [comment]
Remind me in a few days to do this, sounds like a job for me. I must have missed it in feburary and since I've got the *big depression*. so yeah just remind me so that I do it

**Comment by yiancar** [comment]
Closing this as it has been resolved:)
