### ISSUE TITLE
Is VIA dead?

### ISSUE THREAD

**Issue by evyd13** [the-via/keyboards#491]
I'm honestly wondering if it's dead or if you're just taking a break. There's 99 open PR's and the last commit was mid November...

Some statement about this would be helpful, as designers are waiting for their boards to be compatible for over two months now.

**Comment by yoichiro** [comment]
I am very disappointed with this stagnation. I think that the VIA ecosystem has been non-functional since November last year. I hope that the process of VIA should be improved, and I think that I want to contribute somethings I can do. But, many codes of VIA are unfortunately not opened...

**Comment by kb-elmo** [comment]
This tbh.

This tool has become way too important in the community to just leave it to die. 
Especially now that a lot of the KBDfans PCBs come pre-flashed with VIA firmware. People expect this tool to work.  

If the original maintainers don't want to work on it anymore for whatever reason then at least make it open source so that other people can continue the work on it. I'm pretty sure there are quite a few people in this community that would happily help to improve this tool.

**Comment by Wilba6582** [comment]
VIA is not dead. It is currently in active development.

VIA was originally created specifically for wilba.tech PCBs, specifically the Ramaworks M60-A.

It was our decision to make it available to other PCBs, since at present, it works with QMK firmware. This is giving back to the QMK community, should anyone there want to use VIA.

We have absolutely no obligation to provide a free keyboard configuration tool to commercial entities that didn't contribute anything towards it.

We work on VIA development when we have time to do so. If things take longer than you like, complaining about it does not motivate us to work quicker.

**Comment by 2Moons-JP** [comment]
> VIA is not dead. It is currently in active development.
> 
> VIA was originally created specifically for the Ramaworks M60-A, and other wilba.tech PCBs.
> 
> It was our decision to make it available to other PCBs, since at present, it works with QMK firmware. This is giving back to the QMK community, should anyone there want to use VIA.
> 
> We have absolutely no obligation to provide a free keyboard configuration tool to commercial entities that didn't contribute anything towards it.
> 
> We work on VIA development when we have time to do so. If things take longer than you like, complaining about it does not motivate us to work quicker.

That doesn't mean that pull requests for new keyboards couldn't be merged by members of the community that aren't only you specifically. Many people in the community including commercial entities want to give our time and effort to help you do pull requests. This is how we would like to contribute to VIA. I think that this should be separated from development. 

I'm sure many people are happy to donate financially for having the benefit of VIA, especially if it was open source. Many people contribute to QMK in the same way.

**Comment by kb-elmo** [comment]
>It was our decision to make it available to other PCBs, since at present, it works with QMK firmware. This is giving back to the QMK community, should anyone there want to use VIA.

I don't know if you are joking here...
It should be more than obvious that VIA has long surpassed it's role as a "Ramaworks keyboard configurator".
It is supported and used by pretty much every new QMK enabled keyboard that gets released in the community now.

> We have absolutely no obligation to provide a free keyboard configuration tool to commercial entities that didn't contribute anything towards it.

Very funny. 
Nobody can contribute to the project because it is closed source proprietary software.
I am pretty sure that there are more than just a few people in this community that would be happy to help improving VIA if it was open source.
&nbsp;
 
I guess it's time to stop supporting this project.
It's clear that this wasn't intended as an open, community friendly project but rather as a corporate, proprietary piece of software that was just granted usage to other people out of the generosity of it's makers.
Kinda fits the Ramaworks image after all...

Luckily there are better, open-source alternatives out there now.
So there isn't really much need to support this anymore anyways.

**Comment by TweetyDaBird** [comment]
> > It was our decision to make it available to other PCBs, since at present, it works with QMK firmware. This is giving back to the QMK community, should anyone there want to use VIA.
> 
> I don't know if you are joking here...
> It should be more than obvious that VIA has long surpassed it's role as a "Ramaworks keyboard configurator".
> It is supported and used by pretty much every new QMK enabled keyboard that gets released in the community now.
> 
> > We have absolutely no obligation to provide a free keyboard configuration tool to commercial entities that didn't contribute anything towards it.
> 
> Very funny.
> Nobody can contribute to the project because it is closed source proprietary software.
> I am pretty sure that there are more than just a few people in this community that would be happy to help improving VIA if it was open source.
>  
> 
> I guess it's time to stop supporting this project.
> It's clear that this wasn't intended as an open, community friendly project but rather as a corporate, proprietary piece of software that was just granted usage to other people out of the generosity of it's makers.
> Kinda fits the Ramaworks image after all...
> 
> Luckily there are better, open-source alternatives out there now.
> So there isn't really much need to support this anymore anyways.

Well... I'm sure you have a few nice looking keyboard hanging around... How about I pick out the one's I like, and you can ship them to me at your cost? And while you're at it, how about you include some optional keycaps as well... Not the really expensive ones, but you know, not too cheap... I'll email you my shipping address...

Sounds reasonable, right? I mean, I like keyboards, and you are sure to have a few you're not actively using, so why not?

Well... For starters, because they are yours and not mine... And I can't simply make them mine by telling you to share/or demanding you hand them over... That's not how the world works... Just because I want something someone else have, doesn't mean it's mine to take... That's stealing...

Rama/Wilba created VIA, and they own it... It's their decision to make what to do with it, and neither you or anyone else have any right to demand anything from them... What you just did was to put it mildly, rude and offensive...

Now, do I think it would be a good move to make VIA open source? Yes I do...
Do I think it's more than possible a lot of people could contribute to VIA? Yes I do...
Does that mean I have any right to demand it? No, I don't...
Can you take your ball and go play somewhere else? Certainly...

**Comment by kb-elmo** [comment]
@TweetyDaBird you are forgetting a very small but important detail here:

VIA is based on QMK. Which is open source.
VIA wouldn't exist without the work of this community and it would certainly not be as popular and widely used.

90+% of the keyboards currently supported by this tool were ported to it by community members.

I never demanded them to make it open source.
I was just confused about Wilba complaining about nobody contributing to the project when it's first not possible to do that for the configurator and second not at all true on the keyboard side since most of the keyboards in VIA are based on community contributions.
His entire comment reads like a big "Fuck you" to the community because apparently all the community contributions are just nice-to-have and not something that improves this tool.
Without the community work VIA would still just be the Rama keyboard configurator that pretty much nobody used.

That aside what they could at least do even if they don't want to make the configurator open (which I understand is their choice) is to add some community maintainers to the keyboards repository so that porting new boards doesn't take three months.

**Comment by GreekGeorge** [comment]
Switched to via when the tada68 online configurator page died, and I'm not too shabby with coding. 
Started telling everyone I know to switch to via ASAP cause it's UI is so much better.
Shame to see this is what it's become...

**Comment by splitkb** [comment]
VIA is not an open source tool. It is a deliberate decision of the designer of any keyboard to rely upon any tool. Using closed source tools makes you dependant and this should not come as a surprise to you.

VIA fits the goals and keeps being made to fit the goals of the people and organisations that invest in it. That gives no one a right to see feature requests implemented, though they may still provide those who develop VIA with feedback and ideas they may choose to use.

Even if VIA would not see further development for the time being, as long as the keyboards that it officially supports are still supported, then there should be no issue.

**Comment by kb-elmo** [comment]
>Even if VIA would not see further development for the time being, as long as the keyboards that it officially supports are still supported, then there should be no issue.

That's the problem. VIA development isn't keeping up with QMK development anymore and because of that there are bugs in it now which cause boards with an up to date QMK firmware to not work correctly with VIA.

**Comment by Wilba6582** [comment]
@kb-elmo You are reframing my statements as some proof that we do not value contributions from the community, or want VIA to be available to all who want to use it. I disagree.

If people knew the amount of work that @olivia and I have put into VIA and QMK to make it work, maybe you'd have a different opinion.

Now you're referring to a recent bug that got into QMK which broke the keycodes, which I am now dealing with, and talking to the QMK maintainers about.

Just because you and others don't see the work happening doesn't mean it isn't happening.

**Comment by splitkb** [comment]
By keyboards that are officially supported, I do mean the keyboards that are added by the VIA team themselves.

If you want to keep keyboards that at some point worked working, simply revert your local branch back to the point where it worked - Git collected revision history for a reason.

If VIA does not fit your needs, consider moving to an open source alternative like Vial. There is no use in complaining here, however unfortunate.

**Comment by GreekGeorge** [comment]
> We have absolutely no obligation to provide a free keyboard configuration tool to commercial entities that didn't contribute anything towards it.
Well... Maybe if it wasn't closed source people could more easily contribute, instead of individuals adding support for their own keyboards and then relying on a small (? I'm not sure just assuming) team to add features etc.
> VIA was originally created specifically for the Ramaworks M60-A, and other wilba.tech PCBs.
imo the moment it "side tracked" and became a more "community" sourced project, kinda makes sense that it should start marching to the beat of QMK.

**Comment by Wilba6582** [comment]
We are working on a major feature which will allow custom menus/UI to be defined in the keyboard definitions, thus allowing anyone to extend VIA to support any custom firmware features, i.e. knobs, sliders, OLEDs, lighting, etc. This is not an easy task, and it took a while, but it will be rolled out very soon.

The easier thing would be to continue with hard-coded UI in VIA to support custom features, but we decided it was better to implement a solution that will benefit all keyboards added to QMK, not just some.

So please excuse any misunderstanding in my original reply.

I was making a point that we are doing what we can, in the time we have, in between day jobs and other committments, to work on VIA for everyone.

**Comment by lewisflude** [comment]
Interesting discussion here! 

I think people need to remember they are not "owed" free work/maintenance on Via just because it's such a popular tool in the community. I think there is a space in the world for slower moving projects that exist outside of the open source model, and it is absolutely the creators choice to decide how to interface with a community. Managing your own expectations is critical.

Software is really hard work, and finding time between day job, other hobby work and general life can be really difficult to balance. I think we as a community should assign more value to the hard work that's been put in, absolutely for free.

However, being such a pioneer in keyboard-mapping software, it sounds like the project could do with the addition of one or two trusted maintainers to help spread the load and reduce the friction for new boards getting in. I'd also love to know what we as a community can do to support Via given the current development model.

**Comment by TweetyDaBird** [comment]
> @TweetyDaBird you are forgetting a very small but important detail here:
> 
> VIA is based on QMK. Which is open source. It doesn't work without it since VIA doesn't provide any firmware on it's own.
> VIA wouldn't exist without the work of this community and it would certainly not be as popular and widely used.
> 
> 90+% of the keyboards currently supported by this tool were ported to it by community members.
> 
> I never demanded them to make it open source.
> I was just confused about Wilba saying that nobody contributes to the project when it's first not possible to do that for the configurator and second not at all true on the keyboard side since most of the keyboards in VIA are based on community contributions.
> His entire comment reads like a big "Fuck you" to the community because apparently all the community contributions are just some convenience and not something that improves this tool and gives it it's popularity in the first place.
> Without the community work VIA would still just be the Rama keyboard configurator that pretty much nobody used.
> 
> That aside what they could at least do even if they don't want to make the configurator open (which I understand is their choice) is to add some community maintainers to the keyboards repository so that porting new boards doesn't take three months.
>  
> 
> > Can you take your ball and go play somewhere else? Certainly...
> 
> What even is your business here? You never contributed to this project anyways



> @TweetyDaBird you are forgetting a very small but important detail here:
> 
> VIA is based on QMK. Which is open source. It doesn't work without it since VIA doesn't provide any firmware on it's own.
> VIA wouldn't exist without the work of this community and it would certainly not be as popular and widely used.
> 
> 90+% of the keyboards currently supported by this tool were ported to it by community members.
> 
> I never demanded them to make it open source.
> I was just confused about Wilba saying that nobody contributes to the project when it's first not possible to do that for the configurator and second not at all true on the keyboard side since most of the keyboards in VIA are based on community contributions.
> His entire comment reads like a big "Fuck you" to the community because apparently all the community contributions are just some convenience and not something that improves this tool and gives it it's popularity in the first place.
> Without the community work VIA would still just be the Rama keyboard configurator that pretty much nobody used.
> 
> That aside what they could at least do even if they don't want to make the configurator open (which I understand is their choice) is to add some community maintainers to the keyboards repository so that porting new boards doesn't take three months.
>  
> 
> > Can you take your ball and go play somewhere else? Certainly...
> 
> What even is your business here? You never contributed to this project anyways

True... I didn't... I'm more a hardware guy than software, so I'm one of those hoping to use VIA on my keyboards...

Still though, what you put out there in your opinion, has impact on all things created and shared as open source or otherwise... I get your frustration, and I get you are realizing you have in some ways made yourself dependent on a tool that isn't open source, making things difficult in ways, when you don't agree with the opinions of the creators... 

The point was that the entitlement was a bit much... Like I said, I hope there is a move towards open source or more core contributors, but it's not yours or mine decision to make, and the way you were attempting to influence it is in my opinion not the right way of doing it... Carrot or whip... Different results...

**Comment by 2Moons-JP** [comment]
> By keyboards that are officially supported, I do mean the keyboards that are added by the VIA team themselves.
> 
> If you want to keep keyboards that at some point worked working, simply revert your local branch back to the point where it worked - Git collected revision history for a reason.
> 
> If VIA does not fit your needs, consider moving to an open source alternative like Vial.

That's not really the point I'm trying to make personally. Just that VIA is becoming more popular and needs more than one person doing new keyboard approvals. That's fair. 

I'm here to volunteer and contribute my time to doing .json approvals. I'll do it once a week voluntarily. I'll also do keyboard conversions voluntarily, even if it remains closed source. 

It's important for the community that .json approvals happen at least once a month, just due to the sheer volume of keyboards with VIA .json requests and everyone wanting their keyboard to be VIA approved. Currently there are over 7.5 billion people in the world but only one person is doing the approvals. 

I want to give my time and energy to making something the community already loves better and more streamlined. Whether it remains open or closed source really makes no difference to me. Though the long term viability of VIA will be questioned as soon as an open source alternative exists. I hope one day we are allowed to help.

**Comment by mcurren** [comment]
I'm also happy to help in any way I can even though I'm a noob to QMK/C as well (self-taught web dev). 
We are all just head over heals for the VIA UI and concept- it makes using a QMK enabled keyboard infinitely better, so thank you @Wilba6582 & @olivia and all others who have made this project. 🥇

**Comment by FeignMan** [comment]
I'm just passing by because my little brother decided to build me a keyboard based on QMK/VIA. Found this thread while trying to learn more about the stuff that goes into this keyboard.

Just wanted to point out what several people here seem to be missing while defending @wilba's rights to keep the whole thing closed source and not welcoming PRs to a repo who's purpose has obvioulsy grown larger than what was obviously originally intended.

Do the creators of this tool have an obigation to make this open source? None at all, of course and I agree. They have no obigation to what's best for the future of their creation. It's only in the greater good, but I respect their right to shoot themselves in the foot.

No one ever has the obligation to be nice. It's always a choice. You entirely have the option to be an ass to people who've  obviously grown to depend on you. But the repercussions will entirely be yours as well. People WILL take their ball and play elsewhere, without you. When you find yourself alone, you can keep telling yourself that you had no obligation to play nice, but I doubt it'll win you any friends.

Thanks , but no thanks. I don't like this keyboard or my brother nearly enough to compromise on my own principles by encouraging the hubris on display here. I'd encourage the rest of the community to do the same.

**Comment by frisbee23** [comment]
a sentence on the via site explaining that it's not possible to make via work with a new keyboards without changing the closed-source app would be awesome and save people trying to do so some time in the future.

**Comment by kb-elmo** [comment]
> a sentence on the via site explaining that it's not possible to make via work with a new keyboards without changing the closed-source app would be awesome and save people trying to do so some time in the future.

This isn't the case?

All you have to do to add support for a new QMK board is to create a json with the layout matrix and PR that into this repo here.
How that json has to look like is explained in the VIA documentation on the website.

**Comment by 4itor** [comment]
VIA maintainers have all the rights to do whatever they want.

I myself think will be better off using VIAL, Open source alternative to VIA.

https://get.vial.today/

It also supports Tap-Dance, Key Combos and other niceties.

Found it strange no one said it before in this thread.
