### ISSUE TITLE
Think6.5 keymap viewer/layout (?) error

### ISSUE THREAD

**Issue by NotYeMK** [the-via/keyboards#773]
Layout shown for the Think6.5 V2 PCB has some keys overlayed on top of other keys, making it difficult to access. It doesn't show the proper placements of keys for ISO layout(ex. iso enter top half in the wrong row, two keys representing one physical key not in the right place). I am not too keen on how to explain the issue or posting it on Github. 

Screenshots below show the issue of key overlaps and misplacement and show the issue a lot better than I can explain it. 

![](https://i.gyazo.com/c387218c6c25dd42fd8361999df6d924.png)

![](https://i.gyazo.com/e0f7b176675bda6a25de4623b1e768e1.png)

**Comment by kapowaz** [comment]
Came here because I encountered the same bug, and after some investigation it appears as if this issue was introduced with [this change](https://github.com/the-via/keyboards/pull/642/files?diff=unified&w=1). Changing the offending line to this:

```json
"1,14\n\n\n2,0",
```

…fixes this for me. But not having much experience with VIA I’d prefer more familiar were to create a PR :)

**Comment by kb-elmo** [comment]
This was fixed in this PR

https://github.com/the-via/keyboards/pull/691
