### ISSUE TITLE
Support for Massdrop CTRL Keyboard

### ISSUE THREAD

**Issue by dsieradzki** [the-via/keyboards#917]
Hello, 
I'm very new in QMK world. I want to buy keyboard with VIA support and I'm thinking about  Massdrop Ctrl.

I'm wandering if there is possibility to add VIA support to Massdrop CTRL Keyboard?
I downloaded QMK firmware and I saw there is a preprocessor flag "VIA_ENABLE". I have compiled firmware successfully with enabled flag.

There are any technical obstacles to add that support aside from compile QMK with enabled flag and add metadata .json file in VIA?

I can't perform tests because I don't have hardware yet.

**Comment by drashna** [comment]
It's entirely up to massdrop.  Specifically, the issue is that the boards don't support EEPROM natively.   There is a way to fake it (which is what a number of the ARM chips do), but it requires changes to the codebase and to mdloader.  massdrop has no desire to do so.  So no EEPROM support. 

And this is important, because VIA uses the "dynamic keymap" feature to store the keymaps in EEPROM.  Otherwise, you lose any changes if you unplug it and re-plug it in.

**Comment by destructobeam** [comment]
@wilba Does this release [mdloader/tree/1.0.6](https://github.com/Massdrop/mdloader/tree/1.0.6) have any bearing on this issue?

**Comment by noahgaertner** [comment]
My understanding is that it should allow support to be implemented, but I'm unsure how to do that or I'd just submit a PR
That being said I'll probably poke around the docs for the next few weeks and see if I can figure it out, if the official team doesn't add support before then
